name: build-docs
on: [push]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      - run: git clone https://github.com/emuell/luals-docs-gen.git
      - run: cargo run --release -- ../luyoga ../docs/src
        working-directory: luals-docs-gen
      - run: mdbook build
        working-directory: docs